### PR TITLE
Updated focus styles

### LINKED ISSUE #1020: Update focus styles to meet 1.4.11 Non-text Contrast
## What

Update button, link and form input focus styles. Follow GDS styling as closely as possible.

This includes (but isn't limited to):
- Buttons
- Button groups
- Links
- Primary navigation
- Secondary navigation
- Breadcrumbs
- Modal Close (X) buttons
- Full screen modal buttons
- Flash message close (X) buttons
- Pagination links
- Buttons within panels
- Table actions icon links/buttons
- All form inputs (additional thought required for toggles, radios and checkboxes)

## Why 

WCAG 2.1 introduces a new success criteria "1.4.11 Non-Text Contrast" which intends that "any visual effects implemented which are necessary to indicate state, such as whether a component is selected or focused, must also ensure that the information used to identify the control in that state has a minimum 3:1 contrast ratio".

### PR DESCRIPTION
**Pull request by jamesjacobs**
## Focus style updates

This branch contains updates to all focus styles (both form elements and other components/elements) to bring them inline with [1.4.11 Non-Text Contrast](https://www.w3.org/WAI/WCAG21/Understanding/non-text-contrast.html).

The yellow background (#FFDD00) contrasts with the black text (#1E1E1E) with a ratio of 12.37:1, which more than meets AA for [1.4.3: Contrast (minimum)](https://www.w3.org/WAI/WCAG21/Understanding/contrast-minimum). The black underline in conjunction with the yellow background allows contrast to be maintained vs adjacent colours on any state background and also vs previous button/link state colour (for hover/active styles) see [c40](https://www.w3.org/WAI/WCAG21/Techniques/css/C40).

The new focus styles have been tested when used on the various "states" pulsar offers on some components (error, success, warning etc styles).

### 🚨Breaking change 🚨
These new focus styles are contained within a new sass partial, therefore products will need to update their main `pulsar.scss` file to include the new file: `@import 'mixin.focus';`

### Other minor changes:
- Input placeholder colour bumped to meet AA (including state variants)
- Muted text colour bumped to meet AA
- Radio and checkbox state colour bug fixed (previously disabled and state styles were being overridden by more specific CSS and not showing).
- Select2 state styles fixed (previously state styles were missing)
- Breadcrumb font size increased
- Form actions now align correctly to form elements
- Alternative black branding logos added for new focus styles
- Inline/tab nav hit area increased

### Browser tests

- [x] Chrome
- [x] Firefox
- [x] Safari
- [x] Edge
- [x] IE11
- [ ] iOS
- [ ] Android

#### Buttons

Standard button (before)
old button

Standard button (after)
btn

Outline button (before)
Screenshot 2019-10-23 at 14 45 32

Outline button (after)
outline btn

Button group (before)
Screenshot 2019-10-23 at 14 45 08

Button group (after)
btn group

Panel button (before)
Screenshot 2019-10-23 at 15 02 16

Panel button (after)
Screenshot 2019-10-23 at 12 52 33

Toolbar naked buttons (before)
Screenshot 2019-10-23 at 15 08 53

Toolbar naked buttons (after)
Screenshot 2019-10-23 at 12 57 53

#### Links

Secondary nav tabs (before)
Screenshot 2019-10-23 at 14 46 17

Secondary nav tabs (after)
Screenshot 2019-10-24 at 13 52 45

Breadcrumbs (before)
Screenshot 2019-10-23 at 14 46 36

Breadcrumbs (after - size has also been increased)
Screenshot 2019-10-23 at 12 51 05

Standard links (before)
Screenshot 2019-10-23 at 15 01 39

Standard links (after)
Screenshot 2019-10-23 at 12 52 12

Rule conditional block links (before)
Screenshot 2019-10-23 at 15 06 35

Rule conditional block links (after)
Screenshot 2019-10-23 at 12 55 46

#### Flash messages

Before
Screenshot 2019-10-23 at 15 01 22

After
Screenshot 2019-10-23 at 12 51 59

#### Pagination

Before
Screenshot 2019-10-23 at 15 01 53

After
Screenshot 2019-10-23 at 12 52 19

#### Progress lists

Before
Screenshot 2019-10-23 at 15 02 30

After
Screenshot 2019-10-23 at 12 52 40

#### Modals

Close X button (before)
Screenshot 2019-10-23 at 15 02 54

Close X button (after)
Screenshot 2019-10-23 at 12 53 03

Full page modal buttons (before)
Screenshot 2019-10-23 at 15 03 17

Full page modal buttons (after)
Screenshot 2019-10-23 at 12 53 15

Table detail close X (before)
Screenshot 2019-10-24 at 11 21 33

Table detail close X (after)
Screenshot 2019-10-24 at 11 20 47

#### Forms

General text based inputs (before)
Screenshot 2019-10-23 at 15 03 41

General text based inputs (after)
Screenshot 2019-10-23 at 12 54 05

File inputs (before)
Screenshot 2019-10-23 at 15 03 58

File inputs (after)
Screenshot 2019-10-23 at 12 54 20

Colour picker (before)
Screenshot 2019-10-23 at 15 04 23

Colour picker (after)
Screenshot 2019-10-23 at 12 54 24

Select (before)
Screenshot 2019-10-23 at 15 04 33

Select (after)
Screenshot 2019-10-23 at 12 54 29

Select2 (before)
Screenshot 2019-10-23 at 15 04 48

Select2 (after)
Screenshot 2019-10-23 at 12 54 34

Toggle switch (before)
Screenshot 2019-10-23 at 15 05 01

Toggle switch (after)
Screenshot 2019-10-23 at 12 54 40

Range slider (before)
Screenshot 2019-10-23 at 15 05 09

Range slider (after)
Screenshot 2019-10-23 at 12 54 45

Checkbox (before)
Screenshot 2019-10-23 at 15 05 18

Checkbox (after)
Screenshot 2019-10-23 at 12 54 50

Radio (before)
Screenshot 2019-10-23 at 15 05 27

Radio (after)
Screenshot 2019-10-23 at 12 54 54

#### Datatables

TH links (before)
Screenshot 2019-10-23 at 15 07 21

TH links (after)
Screenshot 2019-10-23 at 12 56 11

TH sort (before)
Screenshot 2019-10-23 at 15 08 20

TH sort (after)
Screenshot 2019-10-23 at 12 57 01

#### Main search

Search input (before)
Screenshot 2019-10-23 at 15 08 29

Search input (after)
Screenshot 2019-10-23 at 12 57 44

Search button (before)
Screenshot 2019-10-23 at 15 08 38

Search button (after)
Screenshot 2019-10-23 at 12 57 48

#### Main navigation

Primary links (before)
Screenshot 2019-10-23 at 15 09 06

Primary links (after)
Screenshot 2019-10-23 at 12 58 10

Secondary links (before)
Screenshot 2019-10-23 at 15 09 23

Secondary links (after)
Screenshot 2019-10-23 at 12 58 28

Main logo (before)
Screenshot 2019-10-23 at 16 00 35

Main logo (after)
Screenshot 2019-10-23 at 15 58 51

Resolves #1020

### CODE REVIEW

**Comment by jackbentley** [comment]
Just a few quick observations from the before/after screenshots:

1. Outline buttons seem to lose their outlines on focus. I'd have expected it to look more like the inputs/toggle when in focus and have a solid black border with yellow bg

2. The naked buttons seem to have some curves on focus. Can we make them look more link standard links with no curve and (it looks like it does have anyway) a thicker bottom border - like pagination links

3. This one might be controversial, but I feel like the secondary nav tabs should have the whole tab area clickable and highlight on focus. So they're a bit more like the modal buttons. Aka: make the click/hit area bigger

4. Flash message close button looks a little odd. I feel like it should have some margin on the right to move it away from the side of the flash message so it looks like it's actually inside the message

5. Looks like inputs seem to lose their curves on focus?

6. The search button has a 1px white border above its focus background

Looking good though! Exciting 😃

**Comment by jackbentley** [comment]
What do radio/checkboxes with a label next to them look like? Does the label text also get highlighted?

**Comment by jamesjacobs** [comment]
@jackbentley Re your observations:

1. Outline buttons do indeed lose their outline on focus, this is intended. With these changes, all buttons have consistent focus styles. Links are similar styles but enough to differentiate them from buttons.

2. Naked buttons already have a `border-radius` on `:active`. Its intentional for buttons and link focus styles to be subtly different.

3. I agree, I'll look at that as part of this ticket.

4. Not sure I follow you on this one. The flash close button doesn't overflow the flash, so it is still "inside the message". Adding a `margin-right` on focus would result in a shift in the button position, which wouldn't be ideal. Adding a margin outside of focus would shift it further in, which again wouldn't be ideal.

5. Yes, this is intentional. Paul and I discussed this and alternatives. It's a precursor of things to come and makes things a lot easier when it comes to inputs with appended/prepended icons and buttons. Form input css already has high specificity, this avoids adding more.

6. Sadly this is a cross browser issue due to absolute positioning. I'll take another look at it but it was near impossible to get IE, Edge, Chrome, Firefox and Safari to play nice here.

7. It's a datatables thing for column sorting.

8. Will take a look.

**Comment by jamesjacobs** [comment]
> What do radio/checkboxes with a label next to them look like? Does the label text also get highlighted?

No, only the input element.

**Comment by jamesjacobs** [comment]
> This one might be controversial, but I feel like the secondary nav tabs should have the whole tab area clickable and highlight on focus. So they're a bit more like the modal buttons. Aka: make the click/hit area bigger

Updated to include that change.

**Comment by Stanton** [comment]
Perhaps table header focus would look better with a bit of border-collapse tweaking, but that's probably something we can address separately as it's not strictly the focus style causing it.

Screenshot 2019-10-25 at 10 06 07

**Comment by Stanton** [comment]
@jamesjacobs A conflict has cropped up here, could you verify which change is intended please

**Pull request merged**
