### PR TITLE
Reduce left padding by 10px on indented form groups.

### LINKED ISSUE #228: Indented form groups are indented 10px too far on desktop layouts
screen shot 2016-06-08 at 17 26 03

### PR DESCRIPTION
**Pull request by langy**
Resolves #228

### CODE REVIEW

**Comment by langy** [comment]
screen shot 2016-06-08 at 17 34 48

**Comment by langy** [comment]
CMS-specific Pulsar issue. Closing and fixing there instead.

**Comment by langy** [comment]
Not a CMS-specific issue afterall. Reopening.

**Comment by Stanton** [comment]
👍

**Pull request merged**
