### PR TITLE
Improved focus styles

### PR DESCRIPTION
**Pull request by jamesjacobs**
Focus styles have been improved to further meet 2.4.7 Focus Visible: (Level AA). 

Elements such as buttons, form elements, links, nav items, breadcrumbs and datatable sortable headers now show a orange outline when focused.

### **Examples:**

**Breadcrumbs:**

image

**Buttons:**

image

**Main nav:**

image

**Secondary nav:**

image

**Inputs:**

image

image

image

image

image

image

image

**Links:**

image

**Sortable datatable headers**

image

### CODE REVIEW

**Comment by Stanton** [comment]
Perhaps warning button should use a special variation to maintain a difference in contrast?

screenshot 2018-10-09 at 10 52 46

**Comment by Stanton** [comment]
Button groups not picking up new styles

screenshot 2018-10-09 at 10 54 33

**Comment by Stanton** [comment]
positioning possibly too tight on buttons, makes button corners look odd (which will likely be flagged by QA)

screenshot 2018-10-09 at 10 55 46

**Comment by Stanton** [comment]
top border missing

screenshot 2018-10-09 at 10 57 38

**Comment by Stanton** [comment]
responsive sidebar help icon not picking up styles

screenshot 2018-10-09 at 10 58 40

**Comment by Stanton** [comment]
mobile menu button not picking up styles

screenshot 2018-10-09 at 10 59 13

**Comment by Stanton** [comment]
icon links not picking up styles (couldn't see any component specific styles)

screenshot 2018-10-09 at 11 01 18

**Comment by nvasileiadis** [comment]
Btw I used the Sim Daltonism app to test some colours and I think the yellow tone for the outline is great! Readable every time and with any colours we use! 👍

**Comment by nvasileiadis** [comment]
Are we aware of links get focused when they exist into the disabled state? The same happens and in Masterswitch. Thought we fixed that some time ago

disabledui-linkfocus

**Comment by nvasileiadis** [comment]
rulestablefocus

**Comment by nvasileiadis** [comment]
tablesfocus

Not sure if that is expected

**Comment by nvasileiadis** [comment]
datatablesfocus

**Comment by Stanton** [comment]
https://github.com/jadu/pulsar/pull/897#issuecomment-428144334

Markup may be incorrect here, double check whether links in sortable columns is correct

**Comment by jamesjacobs** [comment]
Updated branch with fixes for the above - apart from the sortable table links, which shouldn't be links imo and need changing to buttons.

**Comment by Stanton** [comment]
Closes #847

**Pull request merged**
