### PR TITLE
474_datatables-do-not-respond-correctly

### PR DESCRIPTION
**Pull request by jamesjacobs**

### CODE REVIEW

**Comment by jamesjacobs** [comment]
Fixes #475 

Tested in both CXM and Lexicon in Chrome, Safari, Firefox, Edge, IE11, IE10 and IE9.

**Comment by Stanton** [comment]
Just a thought, have you checked the settings pattern with this change, that's one of the more complex layouts... http://localhost:3000/app/app.php/lexicon/patterns.html.twig

**Comment by jamesjacobs** [comment]
Fix breaks settings in old IE - will investigate

**Comment by jamesjacobs** [comment]
Added fix for settings. Browser tested fix in Chrome, Safari, Firefox, Edge, IE11, IE10 and IE9.

**Comment by Stanton** [comment]
Did a wraith pass against my baseline last night and found no diffs, might be a good idea to remove the baseline images from the repo and just maintain our own local version for wraith testing.

**Pull request merged**
