### PR TITLE
Add a .gitattributes file

### LINKED ISSUE #238: Add .gitattributes file to reduce size when cloned as a dependency
We include a lot of libs that include tonnes of files that never get used outside of development. These should therefore probably be excluded from the repo when it's cloned as a dependency (via composer, for example).

More info: https://www.reddit.com/r/PHP/comments/2jzp6k/i_dont_need_your_tests_in_my_production

### PR DESCRIPTION
**Pull request by Stanton**
Closes #238

### CODE REVIEW

**Comment by langy** [comment]
👍 , however, the `/libs` dir could probably do with being gone through at some point too (it's currently 22mb in size, likely due to loads of files we'll never use in production)

**Comment by Stanton** [comment]
screen shot 2016-07-01 at 11 25 17

**Comment by langy** [comment]
Also may need testing to make sure the directories specified are actually excluded as I've just been reading about potentially requiring a trailing slash; http://stackoverflow.com/questions/5524731/git-ignoring-gitattributes-pattern

**Comment by langy** [comment]
@Stanton Could you sanity check my commit plz?

**Comment by Stanton** [comment]
Looks ok at a glance, I haven't looked at every line of course.

Not sure how to invoke this through composer, tried adding `prefer-dist` to CMS's composer.json and reinstalling composer deps, but nothing changed...

**Comment by Stanton** [comment]
👍

**Pull request merged**
