### PR TITLE
Change all progress list '-of-type' selectors to '-child' ones instead.

### LINKED ISSUE #62: Progress lists rely on all 'stages' being the same element
Styling is written using `first-of-type` and `last-of-type` selectors. This is fine if they're all the same element type, but if stage cannot be returned to (therefore negating the use of an anchor element and instead using a div, for example), the design breaks.

image

### PR DESCRIPTION
**Pull request by langy**
Resolves #62

### CODE REVIEW

**Comment by langy** [comment]
Updated docs: https://jadu.gitbooks.io/pulsar/content/progress_list.html#mixing-element-types-for-items

**Comment by Stanton** [comment]
:+1: nice catch!

**Comment by Stanton** [comment]
The explanation in the docs doesn't feel entirely necessary to me given there's a complete markup example, we'd expect there to be unwanted layout issues if people stray from the given markup.

**Comment by Stanton** [comment]
In fact, having a second example which has some items as links and some as divs (or whatever) might be more useful for someone implementing a progress list?

**Pull request merged**
