### PR TITLE
Added range slider styles for html range inputs

### PR DESCRIPTION
**Pull request by jamesjacobs**
Currently used in CXM for image zoom.
slider

Haven't added a helper yet as styles are used via `@extend` to style external lib.

Tested in:

- [x] IE Edge
- [x] IE 11
- [x] IE 10
- [x] Safari
- [x] Chrome
- [x] Firefox

Falls back to standard file input in < IE10 so no old IE styles.

### CODE REVIEW

**Comment by Stanton** [comment]
While you've not added a helper here, it feels weird that the class/styles aren't documented... worth adding a doc page in the forms helper section with some examples, and add a ticket to create a helper soon?

**Comment by jamesjacobs** [comment]
@Stanton Originally it was much DRYer, however, combining the vendor specific track and thumb selectors broke the styles. Will take another look and add docs.

**Comment by jamesjacobs** [comment]
You can't combine vendor specific pseudo-elements/classes, see https://www.w3.org/TR/CSS21/syndata.html#rule-sets, specifically

> The selector (see also the section on selectors) consists of everything up to (but not including) the first left curly brace ({). A selector always goes together with a declaration block. When a user agent cannot parse the selector (i.e., it is not valid CSS 2.1), it must ignore the selector and the following declaration block (if any) as well.

**Comment by Stanton** [comment]
Is this one still still waiting on stuff? or ready to merge?

**Comment by jamesjacobs** [comment]
Just making a small change then needs to go back through testing.

**Pull request merged**
